// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL3xY-2NxTp1brkT3FHymVD3Y7-DHVcMo',
    appId: '1:929222259386:web:e4f2f82ab9ebd55bd0c883',
    messagingSenderId: '929222259386',
    projectId: 'authstream-kit-ag',
    authDomain: 'authstream-kit-ag.firebaseapp.com',
    storageBucket: 'authstream-kit-ag.firebasestorage.app',
    measurementId: 'G-458VNBGBCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaFoYShOdwmyLi7vOpeUQWwA4Czxia9Qc',
    appId: '1:929222259386:android:aaa24eabc7af1599d0c883',
    messagingSenderId: '929222259386',
    projectId: 'authstream-kit-ag',
    storageBucket: 'authstream-kit-ag.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAelum6bpYoByuC7RKjboDOTP_ziZ4QlhM',
    appId: '1:929222259386:ios:80e1f2f7131dbc11d0c883',
    messagingSenderId: '929222259386',
    projectId: 'authstream-kit-ag',
    storageBucket: 'authstream-kit-ag.firebasestorage.app',
    iosBundleId: 'com.ag.authstreamKit',
  );

}